/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as governorBravoInterfacesSol from "./GovernorBravoInterfaces.sol";
import type * as test from "./test";

export type { governorBravoInterfacesSol };

export type { test };
export type { GovernorBravoDelegate } from "./GovernorBravoDelegate";
export type { GovernorBravoDelegator } from "./GovernorBravoDelegator";
export type { Hifi } from "./Hifi";
export type { Timelock } from "./Timelock";
